#!/usr/bin/env python3
"""
gen_readmes.py — Auto-generate README.md files for all modules

This tool scans src/py/** and src/js/** directories and generates/updates
README.md files for each module based on code structure and docstrings.

Usage:
    python3 tools/gen_readmes.py

Output:
    README.md files in each module directory
"""

import ast
import sys
from pathlib import Path
from typing import List, Dict, Optional


def extract_module_info(py_file: Path) -> Dict[str, any]:
    """
    Extract module information from a Python file.
    
    Returns:
        Dictionary with module docstring, functions, and classes
    """
    try:
        content = py_file.read_text()
        tree = ast.parse(content)
        
        # Extract module docstring
        module_doc = ast.get_docstring(tree) or "No description available."
        
        # Extract functions
        functions = []
        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef) and not node.name.startswith('_'):
                func_doc = ast.get_docstring(node) or "No description."
                args = [arg.arg for arg in node.args.args]
                functions.append({
                    'name': node.name,
                    'args': args,
                    'doc': func_doc.split('\n')[0]  # First line only
                })
        
        # Extract classes
        classes = []
        for node in ast.walk(tree):
            if isinstance(node, ast.ClassDef) and not node.name.startswith('_'):
                class_doc = ast.get_docstring(node) or "No description."
                classes.append({
                    'name': node.name,
                    'doc': class_doc.split('\n')[0]
                })
        
        return {
            'doc': module_doc,
            'functions': functions,
            'classes': classes
        }
    except Exception as e:
        print(f"Warning: Could not parse {py_file}: {e}", file=sys.stderr)
        return {'doc': 'Error parsing module.', 'functions': [], 'classes': []}


def generate_module_readme(module_dir: Path, py_files: List[Path]) -> str:
    """
    Generate README content for a module directory.
    """
    module_name = module_dir.name
    
    readme = f"""# {module_name.title()} Module

<!-- AUTO:BEGIN -->
*This section is auto-generated by tools/gen_readmes.py*

## Overview

This module contains the following files:

"""
    
    for py_file in py_files:
        info = extract_module_info(py_file)
        readme += f"### `{py_file.name}`\n\n"
        readme += f"{info['doc']}\n\n"
        
        if info['classes']:
            readme += "**Classes:**\n\n"
            for cls in info['classes']:
                readme += f"- `{cls['name']}` — {cls['doc']}\n"
            readme += "\n"
        
        if info['functions']:
            readme += "**Functions:**\n\n"
            for func in info['functions']:
                args_str = ', '.join(func['args'])
                readme += f"- `{func['name']}({args_str})` — {func['doc']}\n"
            readme += "\n"
        
        readme += "---\n\n"
    
    readme += """<!-- AUTO:END -->

## Usage

```python
# Example usage
from {module_name} import SomeClass

# Your code here
```

## Testing

```bash
pytest tests/test_{module_name}/
```

## Dependencies

See `requirements.txt` for module dependencies.

---

*Manual notes can be added here — they will be preserved during regeneration.*
"""
    
    return readme


def scan_and_generate(src_dir: Path):
    """
    Scan source directory and generate READMEs for each module.
    """
    if not src_dir.exists():
        print(f"Warning: {src_dir} does not exist, skipping.", file=sys.stderr)
        return
    
    # Find all subdirectories with Python files
    for module_dir in src_dir.iterdir():
        if not module_dir.is_dir():
            continue
        
        py_files = list(module_dir.glob("*.py"))
        if not py_files:
            continue
        
        print(f"Generating README for: {module_dir.relative_to(src_dir.parent)}")
        
        readme_path = module_dir / "README.md"
        readme_content = generate_module_readme(module_dir, py_files)
        
        readme_path.write_text(readme_content)
        print(f"  ✓ Written to {readme_path}")


def main():
    """Main execution"""
    script_dir = Path(__file__).parent
    project_root = script_dir.parent
    
    print("Scanning for modules...")
    
    # Scan Python modules
    py_src_dir = project_root / "src" / "py"
    if py_src_dir.exists():
        print(f"\nProcessing Python modules in: {py_src_dir}")
        scan_and_generate(py_src_dir)
    
    # Scan JavaScript modules
    js_src_dir = project_root / "src" / "js"
    if js_src_dir.exists():
        print(f"\nProcessing JavaScript modules in: {js_src_dir}")
        print("  Note: JavaScript parsing not yet implemented")
    
    print("\n✓ All module READMEs generated")
    print("\nReview generated files and add manual notes as needed.")


if __name__ == "__main__":
    main()

